//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace linkTimer.FrameWork.WebService.DynamicWebServiceCalling.Bm_Info {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/services/BzService", ConfigurationName="FrameWork.WebService.DynamicWebServiceCalling.Bm_Info.BzServicePortType")]
    public interface BzServicePortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:com.perfect.webservice.BzService.easCWZH", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string easCWZH(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:com.perfect.webservice.impl.BzServiceImpl.easPaymentValid", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string easPaymentValid(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:com.perfect.webservice.BzService.yxCheckState", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string yxCheckState(string json, string uid, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:com.perfect.webservice.impl.BzServiceImpl.sunshineDataPush", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string sunshineDataPush(string json, string uid, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:com.perfect.webservice.BzService.Bm_Info", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string Bm_Info(string systemId, string time);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:com.perfect.webservice.BzService.mh_reimbursement_Info", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string mh_reimbursement_Info(string queryString, string uid, string pwd);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BzServicePortTypeChannel : linkTimer.FrameWork.WebService.DynamicWebServiceCalling.Bm_Info.BzServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BzServicePortTypeClient : System.ServiceModel.ClientBase<linkTimer.FrameWork.WebService.DynamicWebServiceCalling.Bm_Info.BzServicePortType>, linkTimer.FrameWork.WebService.DynamicWebServiceCalling.Bm_Info.BzServicePortType {
        
        public BzServicePortTypeClient() {
        }
        
        public BzServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BzServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BzServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BzServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string easCWZH(string in0, string in1, string in2) {
            return base.Channel.easCWZH(in0, in1, in2);
        }
        
        public string easPaymentValid(string in0, string in1, string in2) {
            return base.Channel.easPaymentValid(in0, in1, in2);
        }
        
        public string yxCheckState(string json, string uid, string pwd) {
            return base.Channel.yxCheckState(json, uid, pwd);
        }
        
        public string sunshineDataPush(string json, string uid, string pwd) {
            return base.Channel.sunshineDataPush(json, uid, pwd);
        }
        
        public string Bm_Info(string systemId, string time) {
            return base.Channel.Bm_Info(systemId, time);
        }
        
        public string mh_reimbursement_Info(string queryString, string uid, string pwd) {
            return base.Channel.mh_reimbursement_Info(queryString, uid, pwd);
        }
    }
}
